import type { AssetDefinition } from '@/lib/types'

export const assetsConfig: AssetDefinition[] = [
  {
    id: 'sbi_account',
    label: 'Bank Account (PSU — SBI, PNB, BOB)',
    icon: 'landmark',
    priority: 1,
    category: 'financial',
  },
  {
    id: 'private_bank_account',
    label: 'Bank Account (Private — HDFC, ICICI, Axis)',
    icon: 'building-2',
    priority: 1,
    category: 'financial',
  },
  {
    id: 'lic_policy',
    label: 'LIC / Life Insurance Policy',
    icon: 'shield',
    priority: 1,
    category: 'financial',
  },
  {
    id: 'epf_account',
    label: 'EPF / Provident Fund (Employee)',
    icon: 'briefcase',
    priority: 2,
    category: 'financial',
  },
  {
    id: 'ppf_account',
    label: 'PPF Account (Public Provident Fund)',
    icon: 'piggy-bank',
    priority: 2,
    category: 'financial',
  },
  {
    id: 'fixed_deposits',
    label: 'Fixed Deposits (FDs)',
    icon: 'banknote',
    priority: 2,
    category: 'financial',
  },
  {
    id: 'mutual_funds_demat',
    label: 'Mutual Funds / Demat / Shares',
    icon: 'trending-up',
    priority: 2,
    category: 'financial',
  },
  {
    id: 'immovable_property',
    label: 'Immovable Property / Land / House',
    icon: 'home',
    priority: 3,
    category: 'property',
  },
  {
    id: 'vehicle',
    label: 'Vehicle (Car / Bike / Truck)',
    icon: 'car',
    priority: 3,
    category: 'property',
  },
  {
    id: 'government_pension',
    label: 'Government / Central Pension',
    icon: 'users',
    priority: 2,
    category: 'financial',
  },
  {
    id: 'nps_account',
    label: 'NPS Account (National Pension System)',
    icon: 'calendar',
    priority: 2,
    category: 'financial',
  },
  {
    id: 'gst_business',
    label: 'GST Registration / Business',
    icon: 'store',
    priority: 1,
    category: 'business',
  },
  {
    id: 'aadhaar_pan',
    label: 'Aadhaar / PAN Card',
    icon: 'id-card',
    priority: 4,
    category: 'identity',
  },
]
