import type { StateDefinition } from '@/lib/types'

export const statesConfig: StateDefinition[] = [
  // States
  { id: 'andhra_pradesh', label: 'Andhra Pradesh', propertyPortalUrl: 'https://igrs.ap.gov.in', propertyPortalName: 'IGRS Andhra Pradesh' },
  { id: 'arunachal_pradesh', label: 'Arunachal Pradesh', propertyPortalUrl: 'https://www.arunachalpradesh.gov.in', propertyPortalName: 'Arunachal Pradesh Gov' },
  { id: 'assam', label: 'Assam', propertyPortalUrl: 'https://revenueassam.nic.in', propertyPortalName: 'Revenue Assam' },
  { id: 'bihar', label: 'Bihar', propertyPortalUrl: 'https://bhumijankari.bihar.gov.in', propertyPortalName: 'Bhumijankari Bihar' },
  { id: 'chhattisgarh', label: 'Chhattisgarh', propertyPortalUrl: 'https://cgregistration.nic.in', propertyPortalName: 'CG Registration' },
  { id: 'goa', label: 'Goa', propertyPortalUrl: 'https://egov.goa.nic.in/igr', propertyPortalName: 'Goa IGR' },
  { id: 'gujarat', label: 'Gujarat', propertyPortalUrl: 'https://garvi.gujarat.gov.in', propertyPortalName: 'GARVI Gujarat' },
  { id: 'haryana', label: 'Haryana', propertyPortalUrl: 'https://jamabandi.nic.in', propertyPortalName: 'Jamabandi Haryana' },
  { id: 'himachal_pradesh', label: 'Himachal Pradesh', propertyPortalUrl: 'https://himachal.nic.in/registration', propertyPortalName: 'HP Registration' },
  { id: 'jharkhand', label: 'Jharkhand', propertyPortalUrl: 'https://jharbhoomi.nic.in', propertyPortalName: 'Jharbhoomi' },
  { id: 'karnataka', label: 'Karnataka', propertyPortalUrl: 'https://kaveri.karnataka.gov.in', propertyPortalName: 'Kaveri Online Services' },
  { id: 'kerala', label: 'Kerala', propertyPortalUrl: 'https://keralaregistration.gov.in', propertyPortalName: 'Kerala Registration' },
  { id: 'madhya_pradesh', label: 'Madhya Pradesh', propertyPortalUrl: 'https://mpigr.gov.in', propertyPortalName: 'MPIGR' },
  { id: 'maharashtra', label: 'Maharashtra', propertyPortalUrl: 'https://igrmaharashtra.gov.in', propertyPortalName: 'IGR Maharashtra' },
  { id: 'manipur', label: 'Manipur', propertyPortalUrl: 'https://manipur.gov.in', propertyPortalName: 'Manipur Gov' },
  { id: 'meghalaya', label: 'Meghalaya', propertyPortalUrl: 'https://meghalaya.gov.in', propertyPortalName: 'Meghalaya Gov' },
  { id: 'mizoram', label: 'Mizoram', propertyPortalUrl: 'https://mizoram.gov.in', propertyPortalName: 'Mizoram Gov' },
  { id: 'nagaland', label: 'Nagaland', propertyPortalUrl: 'https://nagaland.gov.in', propertyPortalName: 'Nagaland Gov' },
  { id: 'odisha', label: 'Odisha', propertyPortalUrl: 'https://registration.odisha.gov.in', propertyPortalName: 'Odisha Registration' },
  { id: 'punjab', label: 'Punjab', propertyPortalUrl: 'https://igrs.punjab.gov.in', propertyPortalName: 'IGRS Punjab' },
  { id: 'rajasthan', label: 'Rajasthan', propertyPortalUrl: 'https://igrs.rajasthan.gov.in', propertyPortalName: 'IGRS Rajasthan' },
  { id: 'sikkim', label: 'Sikkim', propertyPortalUrl: 'https://sikkim.gov.in', propertyPortalName: 'Sikkim Gov' },
  { id: 'tamil_nadu', label: 'Tamil Nadu', propertyPortalUrl: 'https://registration.tn.gov.in', propertyPortalName: 'TN Registration' },
  { id: 'telangana', label: 'Telangana', propertyPortalUrl: 'https://registration.telangana.gov.in', propertyPortalName: 'Telangana Registration' },
  { id: 'tripura', label: 'Tripura', propertyPortalUrl: 'https://igrst.nic.in', propertyPortalName: 'IGRS Tripura' },
  { id: 'uttar_pradesh', label: 'Uttar Pradesh', propertyPortalUrl: 'https://igrsup.gov.in', propertyPortalName: 'IGRS UP' },
  { id: 'uttarakhand', label: 'Uttarakhand', propertyPortalUrl: 'https://uttarakhand.gov.in/stamp', propertyPortalName: 'Uttarakhand Registration' },
  { id: 'west_bengal', label: 'West Bengal', propertyPortalUrl: 'https://wbregistration.gov.in', propertyPortalName: 'WB Registration' },
  // Union Territories
  { id: 'delhi', label: 'Delhi', propertyPortalUrl: 'https://doris.delhigovt.nic.in', propertyPortalName: 'DORIS Delhi' },
  { id: 'andaman_nicobar', label: 'Andaman & Nicobar Islands', propertyPortalUrl: 'https://andaman.gov.in', propertyPortalName: 'Andaman Gov' },
  { id: 'chandigarh', label: 'Chandigarh', propertyPortalUrl: 'https://chandigarh.gov.in', propertyPortalName: 'Chandigarh Gov' },
  { id: 'dadra_nagar_haveli', label: 'Dadra & Nagar Haveli and Daman & Diu', propertyPortalUrl: 'https://dadra.gov.in', propertyPortalName: 'Dadra Gov' },
  { id: 'jammu_kashmir', label: 'Jammu & Kashmir', propertyPortalUrl: 'https://jkregistration.nic.in', propertyPortalName: 'JK Registration' },
  { id: 'ladakh', label: 'Ladakh', propertyPortalUrl: 'https://ladakh.gov.in', propertyPortalName: 'Ladakh Gov' },
  { id: 'lakshadweep', label: 'Lakshadweep', propertyPortalUrl: 'https://lakshadweep.gov.in', propertyPortalName: 'Lakshadweep Gov' },
  { id: 'puducherry', label: 'Puducherry', propertyPortalUrl: 'https://registrationpuducherry.in', propertyPortalName: 'Puducherry Registration' },
]
